### PR TITLE
Fix #8

### LINKED ISSUE #8: Return the error message if "dub build" (during generating json file) fails
It's possible that old versions of a package stop compile by new compiler version. In that case [dub build](https://github.com/symmetryinvestments/dsemver/blob/79f487309bafaa052598dcedf367973d2c58a1f6/source/dsemver/buildinterface.d#L24) should print the error message to user be able to fix the error. In other case instead of fixing of his error user thinks that dsemver fails.

### PR DESCRIPTION
**Pull request by drug007**
Probable fix for #8

### CODE REVIEW

**Comment by burner** [comment]
thank you very much.

Keep the issues and/or fixes coming.

**Comment by burner** [comment]
https://github.com/symmetryinvestments/dsemver/releases/tag/v1.2.0

**Comment by drug007** [comment]
Hmm, it turns out the solution is not good because the output is two mixed message, one about compiler error and another about that selections do not match the dependency specification and suggesting to do `dub upgrade`. I'll try to fix it but currently I have no time.

If selections match the dependency specification it works as expected.

**Comment by burner** [comment]
At least a step in the right direction. Bad output is way better than none at all.

**Pull request merged**
